apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-waf-webapp-settings
  namespace: home-assistant
data:
  99-webapp-settings.conf: |
    # TODO: Home Assistant Web Application Security
    # SecRule REQUEST_URI "@beginsWith /attack-me" "id:1001,phase:1,pass,nolog,ctl:ruleEngine=Off"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-app
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant-app
  template:
    metadata:
      labels:
        app: home-assistant-app
    spec:
      containers:
      - name: home-assistant-waf-sidecar
        image: owasp/modsecurity-crs:nginx-alpine
        ports:
        - containerPort: 8122
        env:
        - name: BACKEND
          value: "http://localhost:8123"
        - name: PORT
          value: "8122"
        - name: SSL_PORT
          value: "4122"
        volumeMounts:
        - name: waf-global-settings-volume
          mountPath: /etc/modsecurity.d/owasp-crs/rules/00-global-settings.conf
          subPath: 00-global-settings.conf
        - name: waf-webapp-settings-volume
          mountPath: /etc/modsecurity.d/owasp-crs/rules/99-webapp-settings.conf
          subPath: 99-webapp-settings.conf
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2025.12.5
        securityContext:
            privileged: true
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: home-assistant-pv-config
        - mountPath: /config/configuration.yaml
          name: home-assistant-configmap-configuration
          subPath: configuration.yaml
        - mountPath: /config/sensors/sensor_homeassistant_specials.yaml
          name: home-assistant-configmap-configuration
          subPath: sensor_homeassistant_specials.yaml
        - mountPath: /config/recorder.yaml
          name: home-assistant-configmap-configuration
          subPath: recorder.yaml
        - mountPath: /etc/localtime
          name: home-assistant-pv-time
          readOnly: true
      volumes:
      - name: waf-global-settings-volume
        configMap:
          name: modsecurity-waf-global-settings
          defaultMode: 0644
      - name: waf-webapp-settings-volume
        configMap:
          name: home-assistant-waf-webapp-settings
          defaultMode: 0644
      - name: home-assistant-configmap-configuration
        configMap:
          name: home-assistant-configuration
          defaultMode: 0644
      - name: home-assistant-pv-config
        persistentVolumeClaim:
          claimName: home-assistant-pv-config
      - name: home-assistant-pv-time
        persistentVolumeClaim:
          claimName: home-assistant-pv-time
          readOnly: true
