# inspired by:
# - https://support.tools/modsecurity-kubernetes-ingress-nginx/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # configure test certificate issueing
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # configure prod certificate issueing
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/acme-challenge-type: "http01"
  name: cloudia-test-ingress
  namespace: cloudia-test
spec:
  ingressClassName: nginx
  rules:
  - host: cloudia-test.osoz.ch
    http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: cloudia-test-echo-svc
            port:
              number: 80
  tls:
  - hosts:
    - cloudia-test.osoz.ch
    # - prometheus.osoz.ch
    secretName: cloudia-test-tls-secret
