# inspired by:
# - https://traefik.io/blog/secure-web-applications-with-traefik-proxy-cert-manager-and-lets-encrypt (ingress resource)
# - https://www.digitalocean.com/community/tutorials/how-to-secure-your-site-in-kubernetes-with-cert-manager-traefik-and-let-s-encrypt (ingress resource)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudia-test-ingress
  namespace: cloudia-test
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    # configure test certificate issueing
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # configure prod certificate issueing
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/acme-challenge-type: "http01"
spec:
  rules:
  - host: cloudia-test.osoz.ch
    http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: cloudia-test-echo-svc
            port:
              number: 80
      - path: /attack-me
        pathType: Prefix
        backend:
          service:
            name: cloudia-test-echo-svc
            port:
              number: 80
  tls:
  - hosts:
    - cloudia-test.osoz.ch
    # - prometheus.osoz.ch
    secretName: cloudia-test-tls-secret
