apiVersion: v1
kind: Service
metadata:
  name: cloudia-test-echo-svc
  namespace: cloudia-test
spec:
  ports:
  - port: 80
    targetPort: 8079
    protocol: TCP
  selector:
    app: cloudia-echo-app
