apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: home-assistant
spec:
  ports:
  - port: 443
    targetPort: 8122
    protocol: TCP
  selector:
    app: home-assistant-app
