---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-service
  namespace: home-assistant
  labels:
    app: zigbee2mqtt
spec:
  type: LoadBalancer
  selector:
    app: zigbee2mqtt
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
